FIx/ID-01/Refactoring Administration Panel
Les-Jailes/Admin_panel pull request #4
Opened 2023-11-07 13:42 UTC by saletG08

what was done is to correct the bug that was presented in the code part and also refactored in a better way the chapters dividing it with their respective jsx and css, refactored in the same way the code that was inside the AdminPanelForm and changed some representative names.

Author: @saletG08 
Code Reviewer: @victor-villca 
Tester: @denisgandel

2023-11-07 14:18 UTC, victor-villca approved these changes

2023-11-07 19:02 UTC, victor-villca requested changes
_Change the the pull request name_ and also the branch name if this action is possible. Due to this branch is up to solve a bug, but the name says "refactor". The name does not match the purpose of the branch. Also some members of the QA team thought this was not solving a bug due to the name.

2023-11-08 13:50 UTC, victor-villca approved these changes

2023-11-08 20:25 UTC, denisgandel approved these changes

2023-11-08 23:52 UTC, merged